name: Workflow Demo

on: 
  #push
  #schedule: 
  #- cron: "* * * * *"
  workflow_dispatch

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID

      run: echo $ACCESS_ID


